language: go

go:
  - 1.x
  - master

install:
  - go get -t -v ./...
  - go install -v ./...

script:
  - go test -v ./...

before_deploy:
  - ./dist.sh

deploy:
  provider: releases
  api_key:
    secure: uzurtCj9Zm/KxyPdeb6PnfXEAPYCuJTgOOoVd82XWdqb81Rbb5n25HQn+YtlTYYZ01eX2JwDKa5nwO4+PQJbVnQdPAN/4RiUozvdVStKnNyKCMtgApJDGLmjFVloky0rbKt70kGCIFAhlueRpKrrOuII/U2Q6i5bjy8KXRAl+5yA13ePS2gBhbAMQuC7BPlNoUk391h982Y59hR2vdNC9QM2OyMsNaZGrDCZ1yZuXmjMZrhTSvkeyeXxIhDLaWR8Qe6RH7OFCl0v4nbAKvinTxsFxOwquKs1dABfjdVXpDxL5JrFhRHOcb5y8CdZMBDTZnSi3s1X5fy7tyCmR3tj4QEXe3EcCVYT+vZ7nXhlvl4DOwjzoKvO4qpRBoHqGaA7w/6Sxij8btQ6euXyDrx7kMguiJKXMHSOqhZqicejlkdR79r6FIFXbOmwTohiz2WDuG6dL4ZRHF1SX6gbQcE72JSCj6YgSn6EwJQQtcWeE411//5kFZ6k9Jp9onoeoble6iOqUjcNgCxPg1VX7eaiQ4L/2BPNJkP0m4YkuGcHWoNkqK6ca2sK7QUy/vLcHt4sCahHDhAViPyxTK6Uj8zVyJACRYBYRdRnJD1Q5kOpeoaJCM+8agXJOkZMU3bxHhXtckvfHnN5EF5wnkfXs3tXLOAUg5wrP1WCbMnhJmUFzVc=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
